# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: Swift

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build-and-test:
    runs-on: macos-latest

    steps:
    # Step 1: Code checkout
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Xcode config
    - name: Set up Xcode
      run: sudo xcode-select -s /Applications/Xcode.app

    # Step 3: SPM dependences
    - name: Resolve Swift Package dependencies
      run: swift package resolve

    # Step 4: Build project
    - name: Build
      run: swift build --enable-test-discovery

    # Step 5: Test execution
    - name: Run tests
      run: swift test --enable-test-discovery
